# Generated by Django 5.2.3 on 2026-06-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['name']},
        ),
    ]
