# Generated by Django 5.2.3 on 2026-06-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_church_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('text', models.TextField()),
                ('translation', models.CharField(default='KJV', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
