# Generated by Django 5.2.3 on 2026-06-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seed_scriptures'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('speaker', models.CharField(max_length=120)),
                ('caption', models.CharField(blank=True, max_length=280)),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField()),
                ('duration_seconds', models.PositiveSmallIntegerField(default=60)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorts', to='api.church')),
                ('sermon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shorts', to='api.sermon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
