# Generated by Django 5.2.3 on 2026-06-27 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sermonshort'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='church',
            name='denomination',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='church',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='church',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='church',
            name='ministry_focus',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='church',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='church',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='auto_save_to_library',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestream',
            name='quality_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='livestream',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='stream_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='tag',
            field=models.CharField(choices=[('healing', 'Healing'), ('guidance', 'Guidance'), ('family', 'Family'), ('finances', 'Finances'), ('praise', 'Praise'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='sermon',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sermon',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sermonshort',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sermonshort',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sermonshort',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChurchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('service', 'Service'), ('bible_study', 'Bible study'), ('prayer', 'Prayer'), ('worship', 'Worship'), ('outreach', 'Outreach'), ('other', 'Other')], default='service', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.church')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.livestream')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='GivingFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giving_funds', to='api.church')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=160)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('frequency', models.CharField(choices=[('one_time', 'One time'), ('monthly', 'Monthly')], default='one_time', max_length=12)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pledged', max_length=12)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='api.church')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='api.givingfund')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_comments', to=settings.AUTH_USER_MODEL)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.prayerrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorshipSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('author', models.CharField(blank=True, max_length=160)),
                ('key', models.CharField(blank=True, max_length=12)),
                ('copyright_info', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worship_songs', to='api.church')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorshipSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='api.worshipsong')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='givingfund',
            constraint=models.UniqueConstraint(fields=('church', 'name'), name='unique_giving_fund_name_per_church'),
        ),
        migrations.AddConstraint(
            model_name='worshipslide',
            constraint=models.UniqueConstraint(fields=('song', 'order'), name='unique_worship_slide_order_per_song'),
        ),
    ]
