# Generated by Django 5.2.3 on 2026-06-27 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_church_cover_image_url_church_denomination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('sandbox', 'Sandbox'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa')], default='sandbox', max_length=20)),
                ('gateway_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checkout_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='created', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='api.donation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
