# Generated by Django 5.2.3 on 2026-07-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_paymentgatewaycheckout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
