# Generated by Django 5.2.3 on 2026-08-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='praise_xp',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('believer', 'Global Believer'), ('creator', 'Gospel Creator'), ('pastor', 'Pastor / Church Leader'), ('artiste', 'Gospel Artiste / Psalmist')], default='believer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_study_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
