# Generated by Django 5.2.3 on 2026-08-26 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_user_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('testimony', 'Testimony'), ('prayer', 'Prayer'), ('reflection', 'Reflection'), ('discussion', 'Discussion')], max_length=12)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('content', models.TextField(max_length=5000)),
                ('scripture_reference', models.CharField(blank=True, max_length=120)),
                ('scripture_text', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('audio_snippet_title', models.CharField(blank=True, max_length=180)),
                ('audio_snippet_duration', models.CharField(blank=True, max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amen_by', models.ManyToManyField(blank=True, related_name='amened_community_posts', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_community_posts', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='api.church')),
                ('glory_by', models.ManyToManyField(blank=True, related_name='gloried_community_posts', to=settings.AUTH_USER_MODEL)),
                ('prayed_by', models.ManyToManyField(blank=True, related_name='prayed_community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amen_by', models.ManyToManyField(blank=True, related_name='amened_community_comments', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.communitypost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
