# Generated by Django 5.2.3 on 2026-10-02 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_audiospace'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_live_streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='api.church'),
        ),
    ]
