# Generated by Django 5.2.3 on 2026-10-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_livestream_created_by_alter_livestream_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='ivs_channel_arn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livestream',
            name='ivs_stream_key_arn',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
