# Generated by Django 5.2.3 on 2026-10-09 19:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_livestreamchatmessage_livestreamviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='audience',
            field=models.CharField(choices=[('all_ages', 'All ages'), ('made_for_kids', 'Made for kids')], default='all_ages', max_length=20),
        ),
        migrations.AddField(
            model_name='sermon',
            name='key_takeaways',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sermon',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='scripture_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sermon',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sermon',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.CreateModel(
            name='SermonUploadSession',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('received_size', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_uploads', to=settings.AUTH_USER_MODEL)),
                ('sermon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_session', to='api.sermon')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
